### ISSUE TITLE
RSLock: Questions regarding 1) Setup Requirements and 2) safety for Multithread Applications & Arc<>

### ISSUE THREAD

**Issue by WarrenN1** [hexcowboy/rslock#10]
My questions are as follows:
1. What are the setup requirements for `rslock`? Do I need to be running a pre-existing redis instance?
2. Is the rslock library safe to use in a Multithreaded context? More specifically, I am using the `rocket` library in rust trying to store the RSLock Manager in an Arc so I can pass it as State to multiple requests. However, the lock keeps failing to acquire.

Any help would be deeply appreciated.

**Comment by hexcowboy** [comment]
1. yes, you need to supply redis URIs - see usage [here](https://github.com/hexcowboy/rslock?tab=readme-ov-file#usage)
2. what is the error you're seeing exactly?

**Comment by WarrenN1** [comment]
Thank you so much for your fast response :). As for question 1:

I am still wondering if it is Multithread safe and how the underlying mechanism works. Does it make use of a connection pool? If not, should I build LockManager for each thread on my server? I am supplying it with urls, but as the example shows local host ones by default, I don't know if the rslock spins up the instances itself or if I need to spin them up.

Also again, do I need to initiate a Redis::Client instance fist or already have a Redis instance running?

As for the error, I just get the LockError enum:
Unavailable.

**Comment by hexcowboy** [comment]
rslock does not start instances of Redis. you will need to supply the URIs of your own Redis instances.
