### ISSUE TITLE
LockManager.lock() panics with a small TTL, when retrying

### ISSUE THREAD

**Issue by matildasmeds** [hexcowboy/rslock#8]
We have a TTL set to five seconds. Calling `LockManager.lock() `with even 1 second of retries, results in panic.

Here is a [minimal example that illustrates the panic](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b674836ad74049685eaa0d079a4912cf) and its conditions. The failing code is in the private `LockManager.exec_or_retry()`, so I have just copied the relevant lines and values to the Playground.

A better behavior would be returning an error with an explanation.
Happy to contribute, if I can get guidance from crate owners/maintainers. 🙏

**Comment by hexcowboy** [comment]
@matildasmeds i believe the panic here is due to line 22 on your playground link:

```rs
    let validity = calculate_validity(5, start_time - one_second);
```

the issue is you are subtracting `1 second` from `now()` which will result in an integer underflow. i'm not sure what your objective is, but maybe you meant to add `1 second` to `now()`?

either way, this panic is not a result of the `rslock` library, and for that reason i'll close this issue. if there is actually an issue here that i'm not seeing, i'd be happy to re-investigate.

**Comment by matildasmeds** [comment]
I appreciate your quick feedback and the opportunity to discuss this further.

I do believe this is a "library feature", in the sense, that if we want to set a short (in our use case 5 seconds) Time To Live for the lock, there is a very real risk that the `LockManager.lock() `will panic, because with enough retries it will (in our case, after 1 second of retries).

In general terms, for me as a library user, it would be amazing if instead of panicking, LockManager.lock() would return a `Result::Err` variant, and in the error explain the details of what failed and if possible why. This would be easier to handle, and more informative, than a panic on integer underflow.

In practical terms, for our use case, we would need a very short TTL for the key, because it is a lock that must be very short lived. We remove it manually too, as soon as we can, but in case that removal fails, the TTL becomes important. In this case, for a TTL of 5 seconds, after 1 second of retries for setting the lock, we have a panic, and that is unfortunately not sustainable for our use case.

**Comment by matildasmeds** [comment]
For clarity's sake let me amend a little bit...

The reason I subtract from the start time when calling this, is to simulate retrying, and effect the same failure that we saw when trying to use the library.

I think, that if I added to the start_time, it would not simulate what happens with retries, with short TTLs.

**Comment by hexcowboy** [comment]
thanks for clarifying the issue @matildasmeds .

i've created a test case that demonstrates your issue

```rs
    #[tokio::test]
    async fn test_lock_with_short_ttl_and_retries() -> Result<()> {
        let (_containers, addresses) = create_clients();

        let mut rl = LockManager::new(addresses.clone());
        // Set a high retry count to ensure retries happen
        rl.set_retry(10, 10); // Retry 10 times with 10 milliseconds delay

        let key = rl.get_unique_lock_id()?;

        // Use a very short TTL
        let ttl = 5; // 5 milliseconds

        // Acquire lock
        let lock_result = rl.lock(&key, ttl).await;

        // Check if the error returned is TtlExceeded
        match lock_result {
            // Err(LockError::TtlExceeded) => (), // Test passes
            _ => panic!("Expected LockError::TtlExceeded, but got {:?}", lock_result),
        }

        Ok(())
    }
```

if you'd like to create a PR for this, feel free to create the new error variant and add logic to the `exec_or_retry` function

**Comment by matildasmeds** [comment]
Would be happy to contribute.

Changing the rerun type to Result will be a breaking change, should that be done for the existing lock method directly, or would you prefer to have another method for this purpose?

**Comment by hexcowboy** [comment]
@matildasmeds thanks for asking. i would prefer a separate method for now, maybe `try_lock()`. in a future major version release we can change `lock()`'s return type

you may change the return type of the private method `exec_or_retry()` to be a Result, and in `lock()` you can just `unwrap()` it. i believe you will need to do the same with `extend()` by creating `try_extend()`

edit: it looks like `lock()` and `extend()` both already return Results with `LockError`, so maybe creation of new `try_` methods won't be necessary. in this case, feel free to change the private `exec_or_retry()` to be a Result and I wouldn't consider it as a breaking change
